// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.8.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

if (System.getenv("BUILDBOT_SCRIPT")) {
    Properties properties = new Properties()

    if (project.rootProject.file('local.properties').exists()) {
        properties.load(project.rootProject.file('local.properties').newDataInputStream())
    }
    properties.setProperty('sdk.dir', System.getenv("ANDROID_HOME"))
    properties.setProperty('cmake.dir', System.getenv("BUILDBOT_CMAKE"))
    if (System.getenv("ANDROID_NDK_HOME")) {
        properties.setProperty('ndk.dir', System.getenv("ANDROID_NDK_HOME"))
    }

    properties.store(project.rootProject.file('local.properties').newDataOutputStream(), '')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
